version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: cart-checkout_DB
    restart: always
    environment:
      POSTGRES_DB: cart-checkout_DB
      POSTGRES_USER: service-user
      POSTGRES_PASSWORD: strong_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
