# No usamos H2 ni ninguna base de datos en memoria
# spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
# spring.datasource.username=sa
# spring.datasource.password=

# Hibernate no crea tablas automáticamente
# spring.jpa.hibernate.ddl-auto=create
# spring.jpa.show-sql=true

# Inicialización de scripts SQL deshabilitada
# spring.sql.init.mode=never
# spring.sql.init.platform=h2
# spring.sql.init.schema-locations=classpath:schema.sql
# spring.sql.init.data-locations=classpath:data.sql

# Consola H2 deshabilitada
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
